description: Use TGI (local or with Hugging Face Inference Endpoints for running LLM inference. When using HF Inference Endpoints, you must provide the name of the endpoint).
providers:
  inference: remote::tgi
  safety: meta-reference
  agentic_system: meta-reference
  memory: meta-reference-faiss
